---
- name: Install VLANs based on Hostname
  eos_vlan:
   vlanid={{item.Vlan}}
   name={{item.VlanDesc}}
   connection={{inventory_hostname}}
   state=present
  when: inventory_hostname == {{item.Hostname}}
  with_items: vlan_config
  register: required_vlans

- name: purge vlans not required
  eos_purge: 
   resource=eos_vlan 
   results='{{ required_vlans|to_nice_json }}'
   connection={{inventory_hostname}}
