---
- name: Install VLANs based on Hostname
  eos_vlan:
   vlanid={{item.Vlan}}
   name={{item.VlanDesc}}
   connection={{inventory_hostname}}
   state=present
  when: inevntory_hostname == {{item.Hostname}}
  with_items: vlan_config
    
